### PR TITLE
New method: Non-sequential Armijo with Fixed Step sizes and negative gradient steps

### LINKED ISSUE #66: Fixed step size gradient descent

### PR DESCRIPTION
**Pull request by VChristian**
# Summary

Implementation of non-sequential Armijo with event driven objective function evaluations, where the inner loop iteration is carried out with a fixed step size and negative gradient directions. The structure and method were implemented with the ability to make it non-monotone, which required additional utility in `src/methods/line_search_helpers/nls_cache_util.jl`. This file was copied from the non-monotone PR. Furthermore, the non sequential armijo method with our adaptive step size method was renamed to `NonSequentialArmijoAdaptiveGD`. **In the future, non-sequential armijo methods should be named `NonSequentialArmijo<step size identifier><step direction identifier>`.**

## Summary of Implementation Changes

- `non_sequential_armijo_fixed_gd` and `NonsequentialArmijoFixedGD` are the new method and `struct`
- `non_sequential_armijo_gd` => `non_sequential_armijo_adaptive_gd` and `NonsequentialArmijoGD` => `NonsequentialArmijoAdaptiveGD`
- Test cases are implemented for the fixed step size and negative gradient direction version of our method
- An additional utility function for test cases is introduced
- Non-monotone utility and testing

Closes #66

### CODE REVIEW

File: src/methods/gd_non_sequential_armijo_adaptive.jl [hunk 1]
```diff
@@ -292,11 +292,35 @@ Conduct the inner loop iteration, modifying `ψjk`, `optData`, and
...
 `optData`; the fields `grad` in `store` gets updated to be the gradient at `ψjk`.
 
+# Method
+
+In what follows, we let ``||\\cdot||_2`` denote the L2-norm. 
+Let ``\\theta_{k}`` for ``k + 1 \\in\\mathbb{N}`` be the ``k^{th}`` iterate
+of the optimization algorithm. Let ``\\delta_{k}, 
+\\tau_{\\mathrm{grad},\\mathrm{lower}}^k, \\tau_{\\mathrm{grad},\\mathrm{upper}}^k``
+be the ``k^{th}`` parameters for the optimization method. 
+The ``k+1^{th}`` iterate and parameters are produced by the following procedure.
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_adaptive.jl:302]: This should be deleted.

File: src/methods/gd_non_sequential_armijo_fixed.jl [hunk 2]
```diff
@@ -0,0 +1,374 @@
...
+- `grad_val_hist::Vector{T}`, stores the norm gradient values at each iterate. 
+    The norm of the gradient evaluated at the initial iterate is stored in the 
+    first position.
+- `stop_iteration::Int64`, the iteration number the algorithm stopped on. The 
+    iterate that induced stopping is saved at `iter_hist[stop_iteration + 1]`.
+
+# Constructors
+
+    NonsequentialArmijoFixedGD(::Type{T}; x0::Vector{T}, δ0::T, δ_upper::T, ρ::T,
+        threshold::T, max_iterations::Int64) where {T}
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_fixed.jl:45]: This is incorrect

File: src/methods/gd_non_sequential_armijo_fixed.jl [hunk 3]
```diff
@@ -0,0 +1,374 @@
...
+################################################################################
+# Utility
+################################################################################
+
+"""
+    inner_loop!(ψjk::S, θk::S, optData::NonsequentialArmijoFixedGD{T}, 
+        progData::P1 where P1 <: AbstractNLPModel{T, S}, 
+        precomp::P2 where P2 <: AbstractPrecompute{T}, 
+        store::P3 where P3 <: AbstractProblemAllocate{T}, 
+        k::Int64; max_iteration = 100) where {T, S}
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_fixed.jl:151]: Does not include `radius`

File: src/methods/gd_non_sequential_armijo_adaptive.jl [hunk 4]
```diff
@@ -281,7 +281,7 @@ function compute_step_size(τ_lower::T, norm_grad::T, local_lipschitz_estimate::
 end
 
 """
-    inner_loop!(ψjk::S, θk::S, optData::NonsequentialArmijoGD{T}, 
+    inner_loop!(ψjk::S, θk::S, optData::NonsequentialArmijoAdaptiveGD{T}, 
         progData::P1 where P1 <: AbstractNLPModel{T, S}, 
         precomp::P2 where P2 <: AbstractPrecompute{T}, 
         store::P3 where P3 <: AbstractProblemAllocate{T},
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_adaptive.jl:287]: This does not include `radius`

File: src/methods/gd_non_sequential_armijo_fixed.jl [hunk 5]
```diff
@@ -0,0 +1,374 @@
...
+        OptimizationMethods.grad!(progData, precomp, store, ψjk)
+        optData.norm_∇F_ψ = norm(store.grad)
+    end
+
+    return j
+end
+
+"""
+    nonsequential_armijo_adaptive_gd(optData::NonsequentialArmijoFixedGD{T},
+        progData::P where P <: AbstractNLPModel{T, S}) where {T, S}
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_fixed.jl:239]: This is incorrect. It should be `nonsequential_armijo_fixed_gd`

File: src/methods/gd_non_sequential_armijo_fixed.jl [hunk 6]
```diff
@@ -0,0 +1,374 @@
...
+
+Implementation of gradient descent with non-sequential armijo and triggering
+    events. The optimization algorithm is specified through `optData`, and
+    applied to the problem `progData`.
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_fixed.jl:243]: with fixed step size and negative gradient directions

File: src/methods/gd_non_sequential_armijo_fixed.jl [hunk 7]
```diff
@@ -0,0 +1,374 @@
...
+In what follows, we let ``||\\cdot||_2`` denote the L2-norm. 
+Let ``\\theta_{k}`` for ``k + 1 \\in\\mathbb{N}`` be the ``k^{th}`` iterate
+of the optimization algorithm. Let ``\\delta_{k}, 
+\\tau_{\\mathrm{grad},\\mathrm{lower}}^k, \\tau_{\\mathrm{grad},\\mathrm{upper}}^k``
+be the ``k^{th}`` parameters for the optimization method. 
+The ``k+1^{th}`` iterate and parameters are produced by the following procedure. 
+
+Let ``\\psi_0^k = \\theta_k``, and recursively define
+```math
+    \\psi_{j}^k = \\psi_0^k - \\sum_{i = 0}^{j-1} \\delta_k \\alpha \\dot F(\\psi_i^k).
```
Comment (VChristian) [inline src/methods/gd_non_sequential_armijo_fixed.jl:256]: Who is `\\alpha`

File: src/methods/line_search_helpers/nls_cache_util.jl [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+Given `array`, find the maximum value given that the elements of `array`
+where shifted left and a new element was added at `sz`. The previous maximum 
+should have position `previous_max_index` in `array`; however, this could be
+an invalid index for `array`.
+
+# Arguments
+
+- `array::Vector{T}`, vector of values of type `T`.
+- `previous_max_index::Int64`, index of the maximum value given that
+    the elements were shifted left to add a new element at `sz`
```
Comment (VChristian) [inline src/methods/line_search_helpers/nls_cache_util.jl:53]: Clarify

File: src/methods/line_search_helpers/non_sequential_armijo.jl [hunk 9]
```diff
@@ -63,4 +63,51 @@ function non_sequential_armijo_condition(F_ψjk::T, reference_value::T,
...
+"""
+    update_algorithm_parameters!(θkp1::S, optData::AbstractOptimizerData{T},
+        achieved_descent::Bool, iter::Int64) where {T, S}
+
+Given that the non-sequential Armijo condition is checked, update the parameters
+    the optimization method. The method updates the following variables in place.
+    
+- `θkp1` is updated to be the next outer loop iterate.
+- `optData` has (potentially) the following fields updated: `δk`, `τ_lower`,
+    `τ_upper`.
```
Comment (VChristian) [inline src/methods/line_search_helpers/non_sequential_armijo.jl:77]: This documentation needs to be better.

File: test/utility/update_algorithm_parameters_test_cases.jl [hunk 10]
```diff
@@ -0,0 +1,510 @@
...
+# Author: Christian Varner
+# Purpose: Testing function for update_algorithm_parameters in
+# src/methods/non_sequential_armijo.jl
+
+using OptimizationMethods, Test
+
+"""
+    update_algorithm_parameters_test_cases(optData::P 
+        where P <: OptimizationMethods.AbstractOptimizerData{T}, dim::Int64,
+        max_iterations::Int64) where {T}
```
Comment (VChristian) [inline test/utility/update_algorithm_parameters_test_cases.jl:11]: Include `constant_fields`

File: test/utility/update_algorithm_parameters_test_cases.jl [hunk 11]
```diff
@@ -0,0 +1,510 @@
...
+
+# Arguments
+
+- `optData::P where P <: OptimizationMethods.AbstractOptimizerData{T}`, `struct`
+    that specifies the method
+- `dim::Int64`, length of the value of the keyword argument `x0` used to initialize
+    the `struct` `optData`. Used for testing.
+- `max_iterations::Int64`, value that was used to initialize the `struct` `optData`.
+    Used for testing.
+
```
Comment (VChristian) [inline test/utility/update_algorithm_parameters_test_cases.jl:23]: Need `## Keyword Arguments`

File: src/methods/gd_non_sequential_armijo_fixed.jl [hunk 12]
```diff
@@ -0,0 +1,374 @@
...
+
+    return NonsequentialArmijoFixedGD{T}(
+        name,                       # name
+        zeros(T, d),                # ∇F_θk
+        T(0),                       # norm_∇F_ψ  
+        α,                          # α
+        δ0,                         # δk
+        δ_upper,                    # δ_upper
+        ρ,                          # ρ
+        zeros(T, M),                # objective_hist
```
[the remark this answers is not in the document]
Comment (VChristian) [reply src/methods/gd_non_sequential_armijo_fixed.jl:129]: This should actually be fine, since the `reference_value` and `reference_value_index`
get initialized to `F(x0)` and `M`, and `objective_hist[M] = F(x0)`. This value
is continuously our reference value until the `M`th accepted iterate. By the
`update_maximum` function, `reference_value == F(x0)` until this case.

File: src/methods/line_search_helpers/nls_cache_util.jl [hunk 13]
```diff
@@ -0,0 +1,85 @@
+# Date: 01/27/2025
+# Author: Christian Varner
+# Purpose: Helper functions to maintain the
+# maximum value for non-monotone line search
+
```
Comment (vp314) [inline src/methods/line_search_helpers/nls_cache_util.jl:5]: Why not use the [CircularArrays](https://www.juliapackages.com/p/circulararrays) package?

**Review by vp314 — CHANGES_REQUESTED** [review]
Everything looks good, my only question is why you did not use the CircularArrays package instead of nls_cache_util

**Review by vp314 — APPROVED** [review]
